export enum TaskActionTypes {
    ADD_TODO_PENDING = "tasks/ADD_TODO_PENDING",
    ADD_TODO_SUCCESS = "tasks/ADD_TODO_SUCCESS",
    ADD_TODO_ERROR = "tasks/ADD_TODO_ERROR",

    TOGGLE_TODO_PENDING = "tasks/TOGGLE_TODO_PENDING",
    TOGGLE_TODO_SUCCESS = "tasks/TOGGLE_TODO_SUCCESS",
    TOGGLE_TODO_ERROR = "tasks/TOGGLE_TODO_ERROR",

    SORT_TODO_PENDING = "tasks/SORT_TODO_PENDING",
    SORT_TODO_SUCCESS = "tasks/SORT_TODO_SUCCESS",
    SORT_TODO_ERROR = "tasks/SORT_TODO_ERROR",

    MOVEUP_TODO_PENDING = "tasks/MOVEUP_TODO_PENDING",
    MOVEUP_TODO_SUCCESS = "tasks/MOVEUP_TODO_SUCCESS",
    MOVEUP_TODO_ERROR = "tasks/MOVEUP_TODO_ERROR",
    
    MOVEDOWN_TODO_PENDING = "tasks/MOVEDOWN_TODO_PENDING",
    MOVEDOWN_TODO_SUCCESS = "tasks/MOVEDOWN_TODO_SUCCESS",
    MOVEDOWN_TODO_ERROR = "tasks/MOVEDOWN_TODO_ERROR"
}
