export enum TaskActionTypes {
    ADD_TODO_PENDING = "tasks/ADD_TODO_PENDING",
    ADD_TODO_SUCCESS = "task/ADD_TODO_SUCCESS",
    ADD_TODO_ERROR = "tasks/ADD_TODO_ERROR",

    TOGGLE_TODO_PENDING = "tasks/TOGGLE_TODO_PENDING",
    TOGGLE_TODO_SUCCESS = "tasks/TOGGLE_TODO_SUCCESS",
    TOGGLE_TODO_ERROR = "tasks/TOGGLE_TODO_ERROR",

    SORT_TODO_PENDING = "tasks/SORT_TODO_PENDING",
    SORT_TODO_SUCCESS = "tasks/SORT_TODO_SUCCESS",
    SORT_TODO_ERROR = "tasks/SORT_TODO_ERROR",

    LOAD_TODOS_SUCCESS = "tasks/LOAD_TODOS_SUCCESS"
}
